"""added candidate status

Revision ID: 63fa82743078
Revises: 15c0adfd2dc0
Create Date: 2026-04-03 10:15:40.401200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fa82743078'
down_revision: Union[str, Sequence[str], None] = '15c0adfd2dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidateID', sa.String(length=50), nullable=False),
    sa.Column('piplineStatus', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['candidateID'], ['candidates.candidateID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_status_id'), 'candidate_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_status_id'), table_name='candidate_status')
    op.drop_table('candidate_status')
    # ### end Alembic commands ###
