"""new update

Revision ID: cda1fe43c923
Revises: 062d495fb7f3
Create Date: 2026-07-09 14:15:52.602319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda1fe43c923'
down_revision: Union[str, Sequence[str], None] = '062d495fb7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_aadhar_forms', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate_aadhar_forms', 'candidate_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.add_column('candidate_education_forms', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate_education_forms', 'candidate_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.add_column('candidate_experience_forms', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate_experience_forms', 'candidate_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.add_column('candidate_pan_forms', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate_pan_forms', 'candidate_documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.alter_column('jobs', 'companyType',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('jobs', 'companyName',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('jobs', 'jobStatus',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'jobStatus',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('jobs', 'companyName',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('jobs', 'companyType',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_constraint(None, 'candidate_pan_forms', type_='foreignkey')
    op.drop_column('candidate_pan_forms', 'document_id')
    op.drop_constraint(None, 'candidate_experience_forms', type_='foreignkey')
    op.drop_column('candidate_experience_forms', 'document_id')
    op.drop_constraint(None, 'candidate_education_forms', type_='foreignkey')
    op.drop_column('candidate_education_forms', 'document_id')
    op.drop_constraint(None, 'candidate_aadhar_forms', type_='foreignkey')
    op.drop_column('candidate_aadhar_forms', 'document_id')
    # ### end Alembic commands ###
