"""updated checklist

Revision ID: 062d495fb7f3
Revises: 6b05244162d2
Create Date: 2026-07-09 11:48:03.413042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062d495fb7f3'
down_revision: Union[str, Sequence[str], None] = '6b05244162d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_checklist_items', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_checklist_items', 'submitted_at')
    # ### end Alembic commands ###
