"""add_hr_assignment_table

Revision ID: 0d0274b3c291
Revises: b36745e519a6
Create Date: 2026-06-08 11:23:34.138886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0274b3c291'
down_revision: Union[str, Sequence[str], None] = 'b36745e519a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(length=50), nullable=False),
    sa.Column('hr1_id', sa.String(length=50), nullable=True),
    sa.Column('hr2_id', sa.String(length=50), nullable=True),
    sa.Column('assigned_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.UserID'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidateID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hr1_id'], ['users.UserID'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['hr2_id'], ['users.UserID'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_assignments_candidate_id'), 'hr_assignments', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_hr_assignments_hr1_id'), 'hr_assignments', ['hr1_id'], unique=False)
    op.create_index(op.f('ix_hr_assignments_hr2_id'), 'hr_assignments', ['hr2_id'], unique=False)
    op.create_index(op.f('ix_hr_assignments_id'), 'hr_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_assignments_id'), table_name='hr_assignments')
    op.drop_index(op.f('ix_hr_assignments_hr2_id'), table_name='hr_assignments')
    op.drop_index(op.f('ix_hr_assignments_hr1_id'), table_name='hr_assignments')
    op.drop_index(op.f('ix_hr_assignments_candidate_id'), table_name='hr_assignments')
    op.drop_table('hr_assignments')
    # ### end Alembic commands ###
