"""Add newsletters table

Revision ID: dcedf384d6f6
Revises: add_candidate_documents
Create Date: 2026-02-27 09:51:06.202940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcedf384d6f6'
down_revision: Union[str, Sequence[str], None] = 'add_candidate_documents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'jobTitle',
               existing_type=sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('jobs', 'jobDescription',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('jobs', 'jobSkills',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('jobs', 'jobExperience',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('jobs', 'jobLocation',
               existing_type=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('jobs', 'hiringManagerID',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.drop_column('jobs', 'jobSalary')
    op.add_column('newsletters', sa.Column('created_by', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'newsletters', 'users', ['created_by'], ['UserID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'newsletters', type_='foreignkey')
    op.drop_column('newsletters', 'created_by')
    op.add_column('jobs', sa.Column('jobSalary', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.alter_column('jobs', 'hiringManagerID',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('jobs', 'jobLocation',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('jobs', 'jobExperience',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('jobs', 'jobSkills',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('jobs', 'jobDescription',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('jobs', 'jobTitle',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
