import logging
"""Agent Registry - All 50+ WROS agents with targets and strategic roles."""

# All 50+ agents organized by tier and domain
AGENT_REGISTRY = {
    # ============================================================
    # TIER 1: CORE RECRUITMENT & CONTROL (4 agents)
    # ============================================================
    "Thunder": {
        "domain": "recruitment",
        "tier": "tier_1_core",
        "agent_id": "thunder_001",
        "owner": "CFO/Recruiting",
        "authority": 3,  # Autonomous execution
        "strategic_importance": "CRITICAL",
        "contributes_to": ["headcount", "revenue"],
        "how_helps_grow": "AI recruiter: sources → screens → interviews → offers → hires → feeds 2000 employee target",
        "fy_target": {"value": 250, "unit": "employees"},
        "y2030_target": {"value": 2000, "unit": "employees"},
        "min_success_rate": 95.0,
        "min_quality_score": 85.0,
        # SPARTAN PHALANX
        "phalanx": "Recruitment",
        "position": 1,
        "left_neighbor": None,  # First in line
        "right_neighbor": "Recruitment Agent",
        "shield_sla": "95% qualified candidates, <2s response",
        "shield_failure_action": "KILL_SWITCH",
        "flank_vulnerabilities": ["rate_limited", "false_positives", "limited_sourcing"],
        "flank_coverage_expected": "job_definitions + sourcing_alternatives",
        "monitor_left_neighbor": False,
        "monitor_right_neighbor": True,
        "shield_watch_interval": 60,
    },
    "Recruitment Agent": {
        "domain": "recruitment",
        "tier": "tier_1_core",
        "agent_id": "recruitment_001",
        "owner": "VP Recruiting",
        "authority": 2,
        "strategic_importance": "CRITICAL",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Job creation + candidate qualification → feeds Thunder with roles and sourcing",
        "fy_target": {"value": 900, "unit": "candidates_qualified"},
        "y2030_target": {"value": 7200, "unit": "candidates"},
        "min_success_rate": 93.0,
        # SPARTAN PHALANX
        "phalanx": "Recruitment",
        "position": 2,
        "left_neighbor": "Thunder",  # I protect Thunder
        "right_neighbor": "Interview Reminder Agent",
        "shield_sla": "98% job quality, 92% candidate match",
        "shield_failure_action": "KILL_SWITCH",
        "flank_vulnerabilities": ["biased_job_descriptions", "incorrect_skills", "missing_coverage"],
        "flank_coverage_expected": "qualified_candidate_stream + market_feedback",
        "monitor_left_neighbor": True,
        "monitor_right_neighbor": True,
        "shield_watch_interval": 60,
    },
    "Supervisor Agent": {
        "domain": "recruitment",
        "tier": "tier_1_core",
        "agent_id": "supervisor_001",
        "owner": "VP Recruiting",
        "authority": 2,
        "strategic_importance": "CRITICAL",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Approves recruiter actions → ensures quality gates → prevents bad hires",
        "fy_target": {"value": 98, "unit": "%_approval_rate"},
        "y2030_target": {"value": 99, "unit": "%_approval_rate"},
        "min_success_rate": 98.0,
    },
    "CEO Dependency Agent": {
        "domain": "governance",
        "tier": "tier_1_core",
        "agent_id": "ceo_dep_001",
        "owner": "CEO",
        "authority": 0,
        "strategic_importance": "CRITICAL",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Reduces CEO dependency → enables organization to operate 30 days without CEO",
        "fy_target": {"value": 5, "unit": "dependencies_eliminated"},
        "y2030_target": {"value": 0, "unit": "critical_dependencies"},
        "min_success_rate": 100.0,
    },

    # ============================================================
    # TIER 2: RESOURCE MANAGEMENT (3 agents)
    # ============================================================
    "Resource Management Agent": {
        "domain": "resource_management",
        "tier": "tier_2_resource",
        "agent_id": "resource_mgmt_001",
        "owner": "SVP Operations",
        "authority": 3,
        "strategic_importance": "CRITICAL",
        "contributes_to": ["revenue", "headcount"],
        "how_helps_grow": "Assigns employees to projects → 80% utilization → generates revenue from headcount",
        "fy_target": {"value": 75, "unit": "%_utilization"},
        "y2030_target": {"value": 80, "unit": "%_utilization"},
        "min_success_rate": 95.0,
    },
    "Core-Pull Conflict Agent": {
        "domain": "resource_management",
        "tier": "tier_2_resource",
        "agent_id": "core_pull_001",
        "owner": "SVP Operations",
        "authority": 2,
        "strategic_importance": "CRITICAL",
        "contributes_to": ["headcount", "revenue"],
        "how_helps_grow": "Enforces no cross-BU CORE borrowing → maintains BU autonomy → enables scaling",
        "fy_target": {"value": 100, "unit": "%_policy_compliance"},
        "y2030_target": {"value": 100, "unit": "%_policy_compliance"},
        "min_success_rate": 99.9,
    },
    "Deployment Agent": {
        "domain": "resource_management",
        "tier": "tier_2_resource",
        "agent_id": "deployment_001",
        "owner": "SVP Operations",
        "authority": 2,
        "strategic_importance": "HIGH",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Executes deployment workflow → matches demand → fills project seats",
        "fy_target": {"value": 90, "unit": "%_match_rate"},
        "y2030_target": {"value": 95, "unit": "%_match_rate"},
        "min_success_rate": 92.0,
    },

    # ============================================================
    # TIER 3: FINANCE (6 agents)
    # ============================================================
    "CFO Agent": {
        "domain": "finance",
        "tier": "tier_3_finance",
        "agent_id": "cfo_001",
        "owner": "CFO",
        "authority": 1,
        "strategic_importance": "CRITICAL",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Tracks $100M revenue target, cash flow, margin, EBITDA for executive visibility",
        "fy_target": {"value": 15_000_000, "unit": "USD_revenue"},
        "y2030_target": {"value": 100_000_000, "unit": "USD_revenue"},
        "min_success_rate": 99.0,
    },
    "Partner ROI Agent": {
        "domain": "finance",
        "tier": "tier_3_finance",
        "agent_id": "partner_roi_001",
        "owner": "CFO",
        "authority": 2,
        "strategic_importance": "HIGH",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Drives partner agency sales, nudges underperforming partners toward targets",
        "fy_target": {"value": 8_000_000, "unit": "USD_partner_revenue"},
        "y2030_target": {"value": 50_000_000, "unit": "USD_partner_revenue"},
        "min_success_rate": 90.0,
    },
    "Opportunity Tracker Agent": {
        "domain": "finance",
        "tier": "tier_3_finance",
        "agent_id": "opp_tracker_001",
        "owner": "VP Sales",
        "authority": 0,
        "strategic_importance": "HIGH",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Tracks sales pipeline → forecasts revenue → feeds $100M target",
        "fy_target": {"value": 15_000_000, "unit": "USD_pipeline"},
        "y2030_target": {"value": 100_000_000, "unit": "USD_pipeline"},
        "min_success_rate": 93.0,
    },
    "Revenue Recognition Agent": {
        "domain": "finance",
        "tier": "tier_3_finance",
        "agent_id": "revenue_rec_001",
        "owner": "Controller",
        "authority": 1,
        "strategic_importance": "HIGH",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Recognizes revenue correctly → accurate financial reporting → investor confidence",
        "fy_target": {"value": 100, "unit": "%_accuracy"},
        "y2030_target": {"value": 100, "unit": "%_accuracy"},
        "min_success_rate": 99.9,
    },
    "Margin Agent": {
        "domain": "finance",
        "tier": "tier_3_finance",
        "agent_id": "margin_001",
        "owner": "CFO",
        "authority": 0,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Calculates gross/contribution margin → identifies profitability drivers",
        "fy_target": {"value": 40, "unit": "%_gross_margin"},
        "y2030_target": {"value": 45, "unit": "%_gross_margin"},
        "min_success_rate": 98.0,
    },
    "Cash Flow Agent": {
        "domain": "finance",
        "tier": "tier_3_finance",
        "agent_id": "cash_001",
        "owner": "CFO",
        "authority": 1,
        "strategic_importance": "HIGH",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Forecasts cash → prevents liquidity crisis → enables growth investments",
        "fy_target": {"value": 5_000_000, "unit": "USD_cash_balance"},
        "y2030_target": {"value": 50_000_000, "unit": "USD_cash_balance"},
        "min_success_rate": 95.0,
    },

    # ============================================================
    # TIER 4: HR & PEOPLE (6 agents)
    # ============================================================
    "HR Agent": {
        "domain": "hr",
        "tier": "tier_4_hr",
        "agent_id": "hr_001",
        "owner": "VP People",
        "authority": 2,
        "strategic_importance": "HIGH",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Employee lifecycle: onboarding → retention → performance → development",
        "fy_target": {"value": 200, "unit": "employees_retained"},
        "y2030_target": {"value": 2000, "unit": "active_employees"},
        "min_success_rate": 95.0,
    },
    "Employee Mental Health Agent": {
        "domain": "hr",
        "tier": "tier_4_hr",
        "agent_id": "mental_health_001",
        "owner": "VP People",
        "authority": 1,
        "strategic_importance": "HIGH",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Maintains wellbeing → 95% retention in first 90 days → reduces attrition",
        "fy_target": {"value": 95, "unit": "%_retention"},
        "y2030_target": {"value": 95, "unit": "%_retention"},
        "min_success_rate": 93.0,
    },
    "Onboarding Agent": {
        "domain": "hr",
        "tier": "tier_4_hr",
        "agent_id": "onboarding_001",
        "owner": "VP People",
        "authority": 2,
        "strategic_importance": "HIGH",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Automates first 90 days → reduces time-to-productivity → improves retention",
        "fy_target": {"value": 90, "unit": "%_on_time"},
        "y2030_target": {"value": 95, "unit": "%_on_time"},
        "min_success_rate": 92.0,
    },
    "Buddy Program Agent": {
        "domain": "hr",
        "tier": "tier_4_hr",
        "agent_id": "buddy_001",
        "owner": "VP People",
        "authority": 2,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Pairs mentors with new employees → engagement → retention",
        "fy_target": {"value": 90, "unit": "%_assignment"},
        "y2030_target": {"value": 95, "unit": "%_assignment"},
        "min_success_rate": 90.0,
    },
    "Performance Agent": {
        "domain": "hr",
        "tier": "tier_4_hr",
        "agent_id": "performance_001",
        "owner": "VP People",
        "authority": 0,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Tracks performance KPIs → identifies high performers → prevents loss",
        "fy_target": {"value": 85, "unit": "%_on_target"},
        "y2030_target": {"value": 90, "unit": "%_on_target"},
        "min_success_rate": 90.0,
    },
    "Retention Risk Agent": {
        "domain": "hr",
        "tier": "tier_4_hr",
        "agent_id": "retention_risk_001",
        "owner": "VP People",
        "authority": 1,
        "strategic_importance": "HIGH",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Identifies flight risk early → enables intervention → prevents attrition",
        "fy_target": {"value": 95, "unit": "%_intervention_rate"},
        "y2030_target": {"value": 98, "unit": "%_intervention_rate"},
        "min_success_rate": 88.0,
    },

    # ============================================================
    # TIER 5: KPI & METRICS (3 agents)
    # ============================================================
    "KPI Agent": {
        "domain": "kpi",
        "tier": "tier_5_kpi",
        "agent_id": "kpi_001",
        "owner": "CEO",
        "authority": 0,
        "strategic_importance": "CRITICAL",
        "contributes_to": ["revenue", "headcount"],
        "how_helps_grow": "Tracks progress toward $100M/2000 targets; alerts if falling behind",
        "fy_target": {"value": 100, "unit": "%_on_track"},
        "y2030_target": {"value": 100, "unit": "%_on_track"},
        "min_success_rate": 99.0,
    },
    "Forecast Agent": {
        "domain": "kpi",
        "tier": "tier_5_kpi",
        "agent_id": "forecast_001",
        "owner": "CFO",
        "authority": 0,
        "strategic_importance": "HIGH",
        "contributes_to": ["revenue", "headcount"],
        "how_helps_grow": "Forecasts quarterly trajectory → predicts gaps → enables course correction",
        "fy_target": {"value": 90, "unit": "%_accuracy"},
        "y2030_target": {"value": 95, "unit": "%_accuracy"},
        "min_success_rate": 90.0,
    },
    "Risk Agent": {
        "domain": "kpi",
        "tier": "tier_5_kpi",
        "agent_id": "risk_001",
        "owner": "CEO",
        "authority": 1,
        "strategic_importance": "CRITICAL",
        "contributes_to": ["revenue", "headcount"],
        "how_helps_grow": "Identifies operational/client/delivery risks → enables mitigation",
        "fy_target": {"value": 100, "unit": "%_detection"},
        "y2030_target": {"value": 100, "unit": "%_detection"},
        "min_success_rate": 95.0,
    },

    # ============================================================
    # TIER 6: SUPPORT & ENGAGEMENT (15+ agents)
    # ============================================================
    "Engagement Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "engagement_001",
        "owner": "VP Marketing",
        "authority": 2,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Candidate engagement → reduces drop-off → improves conversion",
        "fy_target": {"value": 85, "unit": "%_engagement_rate"},
        "y2030_target": {"value": 90, "unit": "%_engagement_rate"},
        "min_success_rate": 88.0,
    },
    "Interview Reminder Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "interview_reminder_001",
        "owner": "Recruiting",
        "authority": 3,
        "strategic_importance": "LOW",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Reduces interview no-shows → improves conversion",
        "fy_target": {"value": 95, "unit": "%_attendance"},
        "y2030_target": {"value": 97, "unit": "%_attendance"},
        "min_success_rate": 90.0,
    },
    "Activity Feed Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "activity_feed_001",
        "owner": "Product",
        "authority": 1,
        "strategic_importance": "LOW",
        "contributes_to": [],
        "how_helps_grow": "Tracks system activity → audit trail → compliance",
        "fy_target": {"value": 100, "unit": "%_uptime"},
        "y2030_target": {"value": 100, "unit": "%_uptime"},
        "min_success_rate": 99.5,
    },
    "Executive Signal Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "exec_signal_001",
        "owner": "CEO",
        "authority": 1,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["revenue", "headcount"],
        "how_helps_grow": "Daily exec signals → CEO visibility → strategic decisions",
        "fy_target": {"value": 100, "unit": "%_accuracy"},
        "y2030_target": {"value": 100, "unit": "%_accuracy"},
        "min_success_rate": 95.0,
    },
    "Ticketing Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "ticketing_001",
        "owner": "Operations",
        "authority": 2,
        "strategic_importance": "LOW",
        "contributes_to": [],
        "how_helps_grow": "Issue tracking → fast resolution → operational efficiency",
        "fy_target": {"value": 24, "unit": "hour_response_time"},
        "y2030_target": {"value": 4, "unit": "hour_response_time"},
        "min_success_rate": 90.0,
    },
    "Help Desk Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "helpdesk_001",
        "owner": "Operations",
        "authority": 2,
        "strategic_importance": "LOW",
        "contributes_to": [],
        "how_helps_grow": "Employee support → reduces friction → improves productivity",
        "fy_target": {"value": 95, "unit": "%_resolution_rate"},
        "y2030_target": {"value": 98, "unit": "%_resolution_rate"},
        "min_success_rate": 88.0,
    },
    "Culture Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "culture_001",
        "owner": "VP People",
        "authority": 1,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Monitors culture health → identifies issues → enables intervention",
        "fy_target": {"value": 80, "unit": "%_engagement_score"},
        "y2030_target": {"value": 85, "unit": "%_engagement_score"},
        "min_success_rate": 85.0,
    },
    "Recognition Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "recognition_001",
        "owner": "VP People",
        "authority": 2,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Recognizes high performers → boosts morale → improves retention",
        "fy_target": {"value": 100, "unit": "%_coverage"},
        "y2030_target": {"value": 100, "unit": "%_coverage"},
        "min_success_rate": 90.0,
    },
    "Weekly Recap Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "weekly_recap_001",
        "owner": "CEO",
        "authority": 0,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["revenue", "headcount"],
        "how_helps_grow": "Weekly snapshot of progress → CEO visibility → strategic tracking",
        "fy_target": {"value": 100, "unit": "%_delivery"},
        "y2030_target": {"value": 100, "unit": "%_delivery"},
        "min_success_rate": 95.0,
    },
    "Feedback Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "feedback_001",
        "owner": "VP People",
        "authority": 1,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["headcount"],
        "how_helps_grow": "Collects feedback → identifies issues → enables continuous improvement",
        "fy_target": {"value": 80, "unit": "%_response_rate"},
        "y2030_target": {"value": 90, "unit": "%_response_rate"},
        "min_success_rate": 85.0,
    },
    "Scrum of Scrums Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "scrum_001",
        "owner": "CEO",
        "authority": 0,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["revenue", "headcount"],
        "how_helps_grow": "8:30 AM standup coordination → ensures alignment across agents",
        "fy_target": {"value": 100, "unit": "%_attendance"},
        "y2030_target": {"value": 100, "unit": "%_attendance"},
        "min_success_rate": 98.0,
    },
    "Reporting Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "reporting_001",
        "owner": "CFO",
        "authority": 0,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Generates reports → investor confidence → fundraising support",
        "fy_target": {"value": 100, "unit": "%_accuracy"},
        "y2030_target": {"value": 100, "unit": "%_accuracy"},
        "min_success_rate": 99.0,
    },
    "Partnership Agent": {
        "domain": "support",
        "tier": "tier_6_support",
        "agent_id": "partnership_001",
        "owner": "VP Partners",
        "authority": 1,
        "strategic_importance": "MEDIUM",
        "contributes_to": ["revenue"],
        "how_helps_grow": "Manages partner relationships → drives partner revenue",
        "fy_target": {"value": 8_000_000, "unit": "USD_partner_revenue"},
        "y2030_target": {"value": 50_000_000, "unit": "USD_partner_revenue"},
        "min_success_rate": 90.0,
    },
}

def get_agent_config(agent_name: str) -> dict:
    """Get configuration for a single agent."""
    return AGENT_REGISTRY.get(agent_name)

def get_all_agents() -> list:
    """Get all agents."""
    return list(AGENT_REGISTRY.keys())

def get_agents_by_tier(tier: str) -> list:
    """Get all agents in a specific tier."""
    return [name for name, config in AGENT_REGISTRY.items() if config["tier"] == tier]

def get_agents_by_domain(domain: str) -> list:
    """Get all agents in a specific domain."""
    return [name for name, config in AGENT_REGISTRY.items() if config["domain"] == domain]

def get_agents_by_importance(importance: str) -> list:
    """Get all agents of a specific strategic importance."""
    return [name for name, config in AGENT_REGISTRY.items() if config["strategic_importance"] == importance]

def count_agents_by_tier() -> dict:
    """Count agents per tier."""
    counts = {}
    for tier in ["tier_1_core", "tier_2_resource", "tier_3_finance", "tier_4_hr", "tier_5_kpi", "tier_6_support"]:
        counts[tier] = len(get_agents_by_tier(tier))
    return counts

def count_total_agents() -> int:
    """Total count of agents."""
    return len(AGENT_REGISTRY)

# Print summary
if __name__ == "__main__":
    print(f"Total Agents: {count_total_agents()}")
    print(f"By Tier: {count_agents_by_tier()}")
    for tier, count in count_agents_by_tier().items():
        print(f"  {tier}: {count} agents")
