import logging
"""added offer letter experiy date

Revision ID: 0d9882968602
Revises: 0e60d8ccefea
Create Date: 2026-05-11 13:24:52.196552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9882968602'
down_revision: Union[str, Sequence[str], None] = '0e60d8ccefea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_letters', sa.Column(
        'offer_expire_date',
        sa.Date(),
        nullable=False,
        server_default='2099-12-31',   # backfills existing rows; update manually as needed
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer_letters', 'offer_expire_date')
    # ### end Alembic commands ###
