import logging
"""added feedback status

Revision ID: 0e60d8ccefea
Revises: 3084c1245670
Create Date: 2026-05-07 09:30:58.008188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e60d8ccefea'
down_revision: Union[str, Sequence[str], None] = '3084c1245670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column(
        'feedback_status',
        sa.String(length=50),
        nullable=False,
        server_default='Pending'   # backfills existing rows; removed after migration
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'feedback_status')
    # ### end Alembic commands ###
