"""changed eductaion form

Revision ID: 15c0adfd2dc0
Revises: 82934bb0b53e
Create Date: 2026-03-26 20:43:13.796674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c0adfd2dc0'
down_revision: Union[str, Sequence[str], None] = '82934bb0b53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_education_forms', 'starting_year',
               existing_type=sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('candidate_education_forms', 'year_of_passing',
               existing_type=sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('candidate_experience_forms', 'year_of_experience',
               existing_type=sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_experience_forms', 'year_of_experience',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('candidate_education_forms', 'year_of_passing',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('candidate_education_forms', 'starting_year',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=4, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
