import logging
"""add_offer_letter_document_links

Revision ID: 2ea2dec44537
Revises: 57959371d37e
Create Date: 2026-05-21 14:49:25.939590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea2dec44537'
down_revision: Union[str, Sequence[str], None] = '57959371d37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_letters', sa.Column('sharepoint_url', sa.Text(), nullable=True))
    op.add_column('offer_letters', sa.Column('download_url', sa.Text(), nullable=True))
    op.add_column('offer_letters', sa.Column('sharepoint_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer_letters', 'sharepoint_path')
    op.drop_column('offer_letters', 'download_url')
    op.drop_column('offer_letters', 'sharepoint_url')
    # ### end Alembic commands ###
