import logging
"""add_candidate_job_applications_table

Revision ID: 3084c1245670
Revises: d530a35a78f9
Create Date: 2026-04-24 09:06:52.226922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3084c1245670'
down_revision: Union[str, Sequence[str], None] = 'd530a35a78f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_job_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('application_status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidateID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.jobID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_job_applications_candidate_id'), 'candidate_job_applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_job_applications_id'), 'candidate_job_applications', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_job_applications_job_id'), 'candidate_job_applications', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_job_applications_job_id'), table_name='candidate_job_applications')
    op.drop_index(op.f('ix_candidate_job_applications_id'), table_name='candidate_job_applications')
    op.drop_index(op.f('ix_candidate_job_applications_candidate_id'), table_name='candidate_job_applications')
    op.drop_table('candidate_job_applications')
    # ### end Alembic commands ###
