import logging
"""offer_letter_approval_and_workflow

Revision ID: 49cffff2c698
Revises: 7b41a9d34a92
Create Date: 2026-05-29 09:15:31.897691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '49cffff2c698'
down_revision: Union[str, Sequence[str], None] = '7b41a9d34a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_panels', sa.Column('job_id', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'interview_panels', 'jobs', ['job_id'], ['jobID'])
    op.add_column('offer_letters', sa.Column('approval_status', sa.String(length=30), nullable=True))
    op.add_column('offer_letters', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('offer_letters', sa.Column('approved_by', sa.String(length=50), nullable=True))
    op.add_column('offer_letters', sa.Column('approval_notes', sa.Text(), nullable=True))
    op.add_column('offer_letters', sa.Column('released_at', sa.DateTime(), nullable=True))
    op.add_column('offer_letters', sa.Column('released_by', sa.String(length=50), nullable=True))
    op.add_column('offer_letters', sa.Column('hm_signature_path', sa.Text(), nullable=True))
    op.add_column('offer_letters', sa.Column('candidate_signature_path', sa.Text(), nullable=True))
    op.add_column('offer_letters', sa.Column('signed_offer_path', sa.Text(), nullable=True))
    op.alter_column('offer_letters', 'offer_status',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_foreign_key(None, 'offer_letters', 'users', ['approved_by'], ['UserID'])
    op.create_foreign_key(None, 'offer_letters', 'users', ['released_by'], ['UserID'])
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer_letters', type_='foreignkey')
    op.drop_constraint(None, 'offer_letters', type_='foreignkey')
    op.alter_column('offer_letters', 'offer_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_column('offer_letters', 'signed_offer_path')
    op.drop_column('offer_letters', 'candidate_signature_path')
    op.drop_column('offer_letters', 'hm_signature_path')
    op.drop_column('offer_letters', 'released_by')
    op.drop_column('offer_letters', 'released_at')
    op.drop_column('offer_letters', 'approval_notes')
    op.drop_column('offer_letters', 'approved_by')
    op.drop_column('offer_letters', 'approved_at')
    op.drop_column('offer_letters', 'approval_status')
    op.drop_constraint(None, 'interview_panels', type_='foreignkey')
    op.drop_column('interview_panels', 'job_id')
    # ### end Alembic commands ###
