import logging
"""added bussiness unit

Revision ID: 5fdf105fb5d0
Revises: 51a6401ffa5e
Create Date: 2026-03-11 09:54:32.926700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5fdf105fb5d0'
down_revision: Union[str, Sequence[str], None] = '51a6401ffa5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_units_id'), 'business_units', ['id'], unique=False)
    op.create_index(op.f('ix_business_units_name'), 'business_units', ['name'], unique=True)
    op.add_column('users', sa.Column('business_unit_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_business_unit_id'), 'users', ['business_unit_id'], unique=False)
    op.create_foreign_key(None, 'users', 'business_units', ['business_unit_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_business_unit_id'), table_name='users')
    op.drop_column('users', 'business_unit_id')
    op.drop_index(op.f('ix_business_units_name'), table_name='business_units')
    op.drop_index(op.f('ix_business_units_id'), table_name='business_units')
    op.drop_table('business_units')
    # ### end Alembic commands ###
