import logging
"""added the job mapping to the candidate

Revision ID: 631b4a5c988a
Revises: 9754bb2bda6b
Create Date: 2026-04-21 09:22:20.105822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631b4a5c988a'
down_revision: Union[str, Sequence[str], None] = '9754bb2bda6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('job_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_candidates_job_id'), 'candidates', ['job_id'], unique=False)
    op.create_foreign_key(None, 'candidates', 'jobs', ['job_id'], ['jobID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_index(op.f('ix_candidates_job_id'), table_name='candidates')
    op.drop_column('candidates', 'job_id')
    # ### end Alembic commands ###
