import logging
"""document verification method

Revision ID: 6b05244162d2
Revises: c7e9a1b3d2f8
Create Date: 2026-07-09 10:20:34.992040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '6b05244162d2'
down_revision: Union[str, Sequence[str], None] = 'c7e9a1b3d2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_documents', 'is_verified',
               existing_type=mssql.BIT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_documents', 'is_verified',
               existing_type=sa.String(length=20),
               type_=mssql.BIT(),
               existing_nullable=True)
    # ### end Alembic commands ###
