import logging
"""added internal note for HR team

Revision ID: 7b41a9d34a92
Revises: 748f54e0f573
Create Date: 2026-05-25 15:35:23.614478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7b41a9d34a92'
down_revision: Union[str, Sequence[str], None] = '748f54e0f573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.String(length=50), nullable=False),
    sa.Column('created_by_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidateID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_notes_candidate_id'), 'internal_notes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_internal_notes_id'), 'internal_notes', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_notes_id'), table_name='internal_notes')
    op.drop_index(op.f('ix_internal_notes_candidate_id'), table_name='internal_notes')
    op.drop_table('internal_notes')
    # ### end Alembic commands ###
