import logging
"""added candidate job title in the candidate table

Revision ID: 82934bb0b53e
Revises: 54fc91852373
Create Date: 2026-03-26 20:28:31.843579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '82934bb0b53e'
down_revision: Union[str, Sequence[str], None] = '54fc91852373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('candidateJobTitle', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'candidateJobTitle')
    # ### end Alembic commands ###
