import logging
"""updated newsletter model

Revision ID: 91a71eaaad47
Revises: 0578656e8c8b
Create Date: 2026-03-06 09:21:51.404260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '91a71eaaad47'
down_revision: Union[str, Sequence[str], None] = '0578656e8c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletter_subscribers', 'is_active',
               existing_type=mssql.BIT(),
               nullable=False)
    op.alter_column('newsletter_subscribers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('newsletter_subscribers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('newsletters', 'status',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('newsletters', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('newsletters', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletters', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('newsletters', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('newsletters', 'status',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('newsletter_subscribers', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('newsletter_subscribers', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('newsletter_subscribers', 'is_active',
               existing_type=mssql.BIT(),
               nullable=True)
    # ### end Alembic commands ###
