import logging
"""add_candidate_employee_type

Revision ID: b8a2a9677931
Revises: 0d0274b3c291
Create Date: 2026-06-08 15:05:06.734132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b8a2a9677931'
down_revision: Union[str, Sequence[str], None] = '0d0274b3c291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('candidateEmployeeType', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'candidateEmployeeType')
    # ### end Alembic commands ###
