import logging
"""updated job

Revision ID: d45af883fdba
Revises: 5fdf105fb5d0
Create Date: 2026-03-12 09:52:10.731477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd45af883fdba'
down_revision: Union[str, Sequence[str], None] = '5fdf105fb5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salaryRange', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('recuriterID', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('business_unit_id', sa.Integer(), nullable=True))
    op.alter_column('jobs', 'noOfPositions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('((1))'))
    op.alter_column('jobs', 'hiringManagerID',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.create_index(op.f('ix_jobs_business_unit_id'), 'jobs', ['business_unit_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'business_units', ['business_unit_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'users', ['recuriterID'], ['UserID'])
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_business_unit_id'), table_name='jobs')
    op.alter_column('jobs', 'hiringManagerID',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
    op.alter_column('jobs', 'noOfPositions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('((1))'))
    op.drop_column('jobs', 'business_unit_id')
    op.drop_column('jobs', 'recuriterID')
    op.drop_column('jobs', 'salaryRange')
    # ### end Alembic commands ###
