import logging
"""add_candidateTempPassword_column

Revision ID: f41ab38cea5a
Revises: 49cffff2c698
Create Date: 2026-06-04 11:00:50.789419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f41ab38cea5a'
down_revision: Union[str, Sequence[str], None] = '49cffff2c698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('candidateTempPassword', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'candidateTempPassword')
    # ### end Alembic commands ###
