export const ROUTES = {
  DASHBOARD: "/",
  THUNDER: "/thunder",
  RESOURCE_MANAGEMENT: "/resource-management",
  CORE_PULL: "/core-pull",
  DEMAND_CONFIRMATION: "/demand-confirmation",
  EMPLOYEES: "/employees",
  CANDIDATES: "/candidates",
  CANDIDATE_CREATE: "/candidates/create",
  CANDIDATE_DETAILS: "/candidates/details",
  JOBS: "/jobs",
  JOB_CREATE: "/jobs/create",
  JOB_DETAILS: "/jobs/details",
  JOB_WORKSPACE: "/jobs/workspace",
  HR_USERS: "/hr-users",
  RBAC: "/rbac",
  OFFERS: "/offers",
  OFFERS_LISTING: "/offers-listing",
};